/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from '@react-spring/three';

import towerScene from '../assets/3d/towerclean.glb';

const Tower = (props) => {
  const towerRef = useRef();

  const { nodes, materials } = useGLTF(towerScene);
  
  return (
    <a.group ref={towerRef} {...props}>
      <mesh
        geometry={nodes.polySurface6.geometry}
        material={materials.lambert2}
        rotation={[1.8, 0, 3.5]}
        scale={0.1}
      />
    </a.group>
  );
}
// useGLTF.preload("/towerclean.glb");

export default Tower;